[package]
name = "slog-kvfilter"
version = "0.5.1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Key values based filter Drain for slog-rs"
keywords = ["slog", "logging", "log", "filter"]
license = "MPL-2.0/MIT/Apache-2.0"
documentation = "https://docs.rs/slog-kvfilter"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/kvfilter"
readme = "README.md"


[dependencies]
slog = "2"
